name: Build JAR on Push

on:
  push:
    branches:
      - my-new-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile and package executable JAR
        run: |
          javac prog1.java
          jar cfe app.jar prog1 prog1.class

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar-${{github.run_number}}
          path: app.jar-${{github.run_number}}